repos:
  # default hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.13
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint-fix
        args:
          - --disable
          - MD013 # line-length
          - MD033 # no-inline-html

  # PyRight (check unresolved imports)
  - repo: local
    hooks:
      - id: nbqa-pyright
        name: nbqa-pyright
        # 'uv run' ensures the hook sees pyproject.toml dependencies
        entry: uv run nbqa pyright
        language: system
        types: [jupyter]

      - id: cleanup-nbqa-artifacts
        name: cleanup nbqa artifacts
        entry: bash -c 'rm -f **/*_pyright_ipynb.py'
        language: system
        pass_filenames: false

  - repo: local
    hooks:
    # Check hyperlinks and external links
    - id: lychee-link-checker
      name: lychee-link-checker
      verbose: true
      language: system
      require_serial: true
      entry: |
        /bin/bash -c '
        if ! command -v lychee >/dev/null 2>&1; then
            echo "--------------------------------------------------------"
            echo "Warning: Lychee (link checker) not found. Skipping ... "
            echo ""
            echo "To enable local link checking, install Lychee:"
            echo "  - MacOS: brew install lychee"
            echo "  - Linux/Windows: https://github.com/lycheeverse/lychee"
            echo "--------------------------------------------------------"
            exit 0
        fi
        lychee "$@"
        ' --
      args:
        - "--quiet"
        - "--no-progress"
        - "--exclude-path=(^|/)\\.[^/]+/"
        - "--root-dir=."
        - "--accept=200,403,429,503"
        - "--exclude=http://localhost:.*"
        - "--exclude=http://127.0.0.1:.*"
        - "--max-retries=5"
        - "--retry-wait-time=10"
        - "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
      types_or: [markdown, python, jupyter]
