name: pre-commit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install Python dependencies via uv sync
        run: uv sync

      - name: Install Lychee (Latest Release)
        run: |
          # Query GitHub API for the latest release tag
          LATEST_TAG=$(curl -s https://api.github.com/repos/lycheeverse/lychee/releases/latest | jq -r .tag_name)
          echo "Installing Lychee version: $LATEST_TAG"

          URL="https://github.com/lycheeverse/lychee/releases/download/${LATEST_TAG}/lychee-x86_64-unknown-linux-gnu.tar.gz"

          # Load the archive, extract into temp folder, move the binary, delete the rest
          mkdir -p lychee_install
          curl -sLO "$URL"
          tar -xzf "lychee-x86_64-unknown-linux-gnu.tar.gz" -C lychee_install --strip-components=1
          sudo mv lychee_install/lychee /usr/local/bin/
          rm -rf lychee_install "lychee-x86_64-unknown-linux-gnu.tar.gz"

          # Verify installation
          echo "Installed Lychee version: $(lychee --version)"

      # Cache lychee results (e.g. to avoid hitting rate limits)
      - name: Restore lychee cache
        uses: actions/cache@v5
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Run pre-commit
        run: uv run pre-commit run --all-files --show-diff-on-failure
        env:
          # to be used in case rate limits are surpassed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
